# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  serverdotnet:
    image: serverdotnet
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5144:5144
      - 80:80
      - 443:443
